# Generated by Django 5.2.17 on 2026-09-01 08:31

import bookkeeping.models
import django.db.models.deletion
import saldovibe.encryption
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Kontonummer')),
                ('name', models.CharField(max_length=200, verbose_name='Kontonamn')),
                ('account_class', models.CharField(choices=[('1', 'Klass 1 – Tillgångar'), ('2', 'Klass 2 – Eget kapital och skulder'), ('3', 'Klass 3 – Rörelsens intäkter'), ('4', 'Klass 4 – Varuinköp och tillverkning'), ('5', 'Klass 5 – Övriga externa kostnader'), ('6', 'Klass 6 – Övriga externa kostnader'), ('7', 'Klass 7 – Anställda och personalkostnader'), ('8', 'Klass 8 – Finansiella och andra poster'), ('9', 'Klass 9 - Årets resultat'), ('10', 'Klass 10 – Bokslutsdispositioner och skatter')], max_length=2, verbose_name='Kontoklass')),
                ('vat_field_code', models.CharField(blank=True, choices=[('', 'Ingen'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('10', '10'), ('11', '11'), ('12', '12'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('30', '30'), ('31', '31'), ('32', '32'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('48', '48')], default='', max_length=2, verbose_name='Momsfält (Skatteverket)')),
                ('sru_code', models.CharField(blank=True, default='', help_text='SRU-kod för Skatteverkets standardiserade räkenskapsutdrag (t.ex. 7011)', max_length=10, verbose_name='SRU-kod')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('include_in_liquidity_forecast', models.BooleanField(blank=True, default=None, help_text='Styr om kontots saldo räknas med i dashboardens likviditetsprognos. Lämnas det tomt används standardvalet: bankkonton (193x) med ett saldo skilt från noll.', null=True, verbose_name='Inkludera i likviditetsprognos')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Konton',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AccountingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Slutdatum')),
            ],
            options={
                'verbose_name': 'Räkenskapsår',
                'verbose_name_plural': 'Räkenskapsår',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('description', models.CharField(max_length=500, verbose_name='Beskrivning')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referens/Verifikationsnr')),
                ('source', models.CharField(choices=[('manual', 'Manuell registrering'), ('bank', 'Bank/kassa'), ('sales_invoice', 'Kundfaktura'), ('supplier_invoice', 'Leverantörsfaktura'), ('expense', 'Utlägg'), ('payroll', 'Lön'), ('vat', 'Moms'), ('fixed_asset', 'Anläggningstillgång'), ('sie_import', 'Import (SIE/SI)'), ('year_end', 'Bokslut')], default='manual', max_length=20, verbose_name='Källa')),
                ('voucher_series', models.CharField(blank=True, max_length=10, verbose_name='Verifikationsserie')),
                ('voucher_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verifikationsnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verifikation',
                'verbose_name_plural': 'Verifikationer',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mallnamn')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Beskrivning')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='Katalogid')),
                ('source_url', models.URLField(blank=True, verbose_name='Källa')),
                ('base_amount_label', models.CharField(blank=True, max_length=100, verbose_name='Etikett för basbelopp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verifikationsmall',
                'verbose_name_plural': 'Verifikationsmallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_debit', models.BooleanField(default=False, verbose_name='Debet')),
                ('is_credit', models.BooleanField(default=False, verbose_name='Kredit')),
                ('amount_rule', models.CharField(choices=[('none', 'Fylls i manuellt'), ('percent', 'Procent av basbeloppet'), ('remainder', 'Resterande belopp')], default='none', max_length=20, verbose_name='Beloppsregel')),
                ('amount_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Procent av basbelopp')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mallrad',
                'verbose_name_plural': 'Mallrader',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='A', max_length=10, verbose_name='Serie')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Nästa verifikationsnummer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Verifikationsserie',
                'verbose_name_plural': 'Verifikationsserier',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSeriesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manuell registrering'), ('bank', 'Bank/kassa'), ('sales_invoice', 'Kundfaktura'), ('supplier_invoice', 'Leverantörsfaktura'), ('expense', 'Utlägg'), ('payroll', 'Lön'), ('vat', 'Moms'), ('fixed_asset', 'Anläggningstillgång'), ('sie_import', 'Import (SIE/SI)'), ('year_end', 'Bokslut')], max_length=20, verbose_name='Källa')),
                ('series_code', models.CharField(max_length=10, verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Verifikationsserieregel',
                'verbose_name_plural': 'Verifikationsserieregler',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Företagsnamn')),
                ('org_number', models.CharField(blank=True, max_length=50, verbose_name='Organisationsnummer')),
                ('legal_form', models.CharField(blank=True, choices=[('aktiebolag', 'Aktiebolag'), ('enskild_firma', 'Enskild firma')], default='', max_length=20, verbose_name='Bolagsform')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='Momsregistreringsnummer')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adress')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postnummer')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('country_code', models.CharField(blank=True, default='SE', max_length=2, verbose_name='Landskod (ISO 3166-1 alpha-2)')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('bankgiro', models.CharField(blank=True, max_length=50, verbose_name='Bankgiro')),
                ('plusgiro', models.CharField(blank=True, max_length=50, verbose_name='Plusgiro')),
                ('reminder_fee', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Föreslagen avgift när en betalningspåminnelse skrivs ut.', max_digits=10, verbose_name='Påminnelseavgift')),
                ('company_icon', models.FileField(blank=True, upload_to='company_icons/', verbose_name='Företagsikon')),
                ('vat_reporting_period', models.CharField(blank=True, choices=[('none', 'Ingen momsredovisning'), ('monthly', 'Månadsvis'), ('quarterly', 'Kvartalsvis'), ('annual', 'Årsvis')], default='none', max_length=20, verbose_name='Momsredovisning')),
                ('vat_start_date', models.DateField(blank=True, null=True, verbose_name='Momsstartdatum')),
                ('email_fetch_enabled', models.BooleanField(default=False, verbose_name='Hämta e-postbilagor')),
                ('email_fetch_provider', models.CharField(blank=True, choices=[('', 'Ingen'), ('gmail', 'Gmail'), ('outlook', 'Outlook')], default='', max_length=20, verbose_name='E-postleverantör')),
                ('email_fetch_address', models.EmailField(blank=True, max_length=254, verbose_name='E-postkonto')),
                ('email_fetch_password', saldovibe.encryption.EncryptedTextField(blank=True, verbose_name='App-lösenord')),
                ('email_fetch_oauth_tenant_id', models.CharField(blank=True, max_length=255, verbose_name='Microsoft 365 Tenant ID')),
                ('email_fetch_oauth_client_id', models.CharField(blank=True, max_length=255, verbose_name='Microsoft 365 Client ID')),
                ('email_fetch_oauth_client_secret', saldovibe.encryption.EncryptedTextField(blank=True, verbose_name='Microsoft 365 Client Secret')),
                ('email_fetch_folder', models.CharField(blank=True, default='INBOX', max_length=100, verbose_name='Inkorgsmapp')),
                ('email_fetch_last_error', models.TextField(blank=True, default='', verbose_name='Senaste importfel')),
                ('email_fetch_last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Senaste importfel vid')),
                ('email_send_provider', models.CharField(blank=True, choices=[('', 'Ingen'), ('smtp', 'SMTP'), ('graph', 'Microsoft 365 (Graph)')], default='', max_length=20, verbose_name='Utgående e-post')),
                ('email_send_from', models.EmailField(blank=True, max_length=254, verbose_name='Avsändaradress')),
                ('email_send_smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP-server')),
                ('email_send_smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP-port')),
                ('email_send_smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP-användarnamn')),
                ('email_send_smtp_password', saldovibe.encryption.EncryptedTextField(blank=True, verbose_name='SMTP-lösenord')),
                ('email_send_smtp_use_tls', models.BooleanField(default=True, verbose_name='STARTTLS')),
                ('email_notify_provider', models.CharField(blank=True, choices=[('', 'Systemkontot (standard)'), ('outgoing', 'Samma som utgående e-post'), ('smtp', 'Eget SMTP-konto'), ('graph', 'Microsoft 365 (Graph), egen brevlåda')], default='', max_length=20, verbose_name='Notiskonto')),
                ('email_notify_from', models.EmailField(blank=True, max_length=254, verbose_name='Avsändaradress (notiser)')),
                ('email_notify_smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP-server (notiser)')),
                ('email_notify_smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP-port (notiser)')),
                ('email_notify_smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP-användarnamn (notiser)')),
                ('email_notify_smtp_password', saldovibe.encryption.EncryptedTextField(blank=True, verbose_name='SMTP-lösenord (notiser)')),
                ('email_notify_smtp_use_tls', models.BooleanField(default=True, verbose_name='STARTTLS (notiser)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
            options={
                'verbose_name': 'Företag',
                'verbose_name_plural': 'Företag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Månad')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Belopp')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='bookkeeping.account', verbose_name='Konto')),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Budgetrad',
                'verbose_name_plural': 'Budgetrader',
                'ordering': ['accounting_year', 'account__number', 'month'],
            },
        ),
        migrations.AddField(
            model_name='accountingyear',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_years', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Från och med')),
                ('end_date', models.DateField(verbose_name='Till och med')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('running', 'Pågår'), ('completed', 'Klar'), ('failed', 'Misslyckades')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Felmeddelande')),
                ('file', models.FileField(blank=True, storage=bookkeeping.models.export_bundle_storage, upload_to='%Y/%m/', verbose_name='Fil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Startad')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Klar')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Sedd')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='bookkeeping.company', verbose_name='Företag')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Startad av')),
            ],
            options={
                'verbose_name': 'Exportpaket',
                'verbose_name_plural': 'Exportpaket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Debet')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Kredit')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Beskrivning')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.account', verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Konteringsrad',
                'verbose_name_plural': 'Konteringsrader',
            },
        ),
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period slut')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Låst')),
                ('reason', models.CharField(max_length=255, verbose_name='Orsak (låsning)')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Låst vid')),
                ('reopened_reason', models.CharField(blank=True, max_length=255, verbose_name='Orsak (upplåsning)')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='Upplåst vid')),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_locks', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_locks', to='bookkeeping.company', verbose_name='Företag')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_locks_created', to=settings.AUTH_USER_MODEL, verbose_name='Låst av')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_locks_reopened', to=settings.AUTH_USER_MODEL, verbose_name='Upplåst av')),
            ],
            options={
                'verbose_name': 'Periodlås',
                'verbose_name_plural': 'Periodlås',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('invoice', 'Faktura'), ('reminder', 'Betalningspåminnelse'), ('digest', 'Daglig notissammanfattning')], max_length=20, verbose_name='Typ')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Mottagare')),
                ('subject', models.CharField(max_length=255, verbose_name='Ämne')),
                ('status', models.CharField(choices=[('sent', 'Skickad'), ('failed', 'Misslyckad')], max_length=10, verbose_name='Status')),
                ('error', models.TextField(blank=True, default='', verbose_name='Felmeddelande')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skickad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='bookkeeping.company', verbose_name='Företag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Skickad av')),
            ],
            options={
                'verbose_name': 'Skickat e-postmeddelande',
                'verbose_name_plural': 'Skickade e-postmeddelanden',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
