# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
        ('bookkeeping', '0001_initial'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='invoicing.invoice', verbose_name='Faktura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='accounting_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='attachments.transactionattachment', verbose_name='Bilagor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='bookkeeping.transaction', verbose_name='Korrigering av'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Skapad av'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bookkeeping.transaction'),
        ),
        migrations.AddField(
            model_name='verificationtemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_templates', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='verificationtemplateentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.account', verbose_name='Konto'),
        ),
        migrations.AddField(
            model_name='verificationtemplateentry',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bookkeeping.verificationtemplate', verbose_name='Mall'),
        ),
        migrations.AddField(
            model_name='voucherseries',
            name='accounting_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_series', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår'),
        ),
        migrations.AddField(
            model_name='voucherseries',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_series', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='voucherseriesrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_series_rules', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('accounting_year', 'account', 'month'), name='uniq_budget_line_per_year_account_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_line_month_1_12'),
        ),
        migrations.AddConstraint(
            model_name='accountingyear',
            constraint=models.UniqueConstraint(fields=('company', 'end_date'), name='uniq_year_per_company'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_account_per_company'),
        ),
        migrations.AddConstraint(
            model_name='periodlock',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='period_lock_end_after_or_equal_start'),
        ),
        migrations.AddConstraint(
            model_name='periodlock',
            constraint=models.UniqueConstraint(fields=('company', 'accounting_year', 'period_start', 'period_end'), name='uniq_period_lock_range_per_year'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('accounting_year', 'voucher_series', 'voucher_number'), name='uniq_voucher_number_per_year_series'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journal_entry_not_both_debit_and_credit'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='journal_entry_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='verificationtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_verification_template_per_company'),
        ),
        migrations.AddConstraint(
            model_name='verificationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('company', 'slug'), name='uniq_verification_template_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='verificationtemplateentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_debit', True), ('is_credit', False)), models.Q(('is_debit', False), ('is_credit', True)), _connector='OR'), name='verification_template_entry_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='voucherseries',
            constraint=models.UniqueConstraint(fields=('company', 'accounting_year', 'code'), name='uniq_voucher_series_per_year'),
        ),
        migrations.AddConstraint(
            model_name='voucherseriesrule',
            constraint=models.UniqueConstraint(fields=('company', 'source'), name='uniq_voucher_series_rule_per_company_source'),
        ),
    ]
