# Generated by Django 5.2.17 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='purpose',
            field=models.CharField(choices=[('invoice', 'Faktura'), ('reminder', 'Betalningspåminnelse'), ('digest', 'Daglig notissammanfattning'), ('salary', 'Lönespecifikation')], max_length=20, verbose_name='Typ'),
        ),
    ]
