# Generated by Django 5.2.17 on 2026-09-27 21:40

import saldovibe.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_fetch_imap_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP-server'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_fetch_imap_port',
            field=models.PositiveIntegerField(default=993, verbose_name='IMAP-port'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_fetch_imap_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP-användarnamn'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_fetch_password',
            field=saldovibe.encryption.EncryptedTextField(blank=True, verbose_name='Lösenord'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_fetch_provider',
            field=models.CharField(blank=True, choices=[('', 'Ingen'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'Annan IMAP-server')], default='', max_length=20, verbose_name='E-postleverantör'),
        ),
    ]
