# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatCloseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Periodstart')),
                ('period_end', models.DateField(verbose_name='Periodslut')),
                ('vat_boxes', models.JSONField(default=dict, verbose_name='Momsrutor')),
                ('source_transaction_ids', models.JSONField(default=list, verbose_name='Källverifikationer')),
                ('source_fingerprint', models.CharField(max_length=64, verbose_name='Källfingeravtryck')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Stängd vid')),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_close_snapshots', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_close_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Stängd av')),
                ('closed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_close_snapshots', to='bookkeeping.transaction', verbose_name='Stängningsverifikation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_close_snapshots', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Momsstängningsbevis',
                'verbose_name_plural': 'Momsstängningsbevis',
                'ordering': ['-period_start', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'accounting_year', 'period_start', 'period_end'), name='uniq_vat_close_snapshot_per_period')],
            },
        ),
    ]
