"""
Django settings for saldovibe project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import base64
import hashlib
import os
from pathlib import Path
from urllib.parse import urlparse

from .runtime import get_project_root, get_runtime_data_dir

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = get_project_root()
DATA_DIR = get_runtime_data_dir(BASE_DIR)


def _env_flag(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value in {"1", "true", "True", "yes", "on"}


def _split_csv_env(name, default=""):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


def _public_url():
    return os.getenv("SALDOVIBE_PUBLIC_URL", "").strip()


def _allowed_hosts():
    explicit_hosts = _split_csv_env("DJANGO_ALLOWED_HOSTS")
    if explicit_hosts:
        return explicit_hosts

    public_url = _public_url()
    if public_url:
        parsed_url = urlparse(public_url)
        if parsed_url.hostname:
            return [parsed_url.hostname]

    return _split_csv_env("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,[::1]")


def _csrf_trusted_origins():
    explicit_origins = _split_csv_env("DJANGO_CSRF_TRUSTED_ORIGINS")
    if explicit_origins:
        return explicit_origins

    public_url = _public_url()
    if public_url:
        parsed_url = urlparse(public_url)
        if parsed_url.scheme and parsed_url.netloc:
            return [f"{parsed_url.scheme}://{parsed_url.netloc}"]

    return []


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in production; the fallback below is public (it is in
# version control) and only acceptable for local development and tests.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or "django-insecure-2)f#j6^$_n@u$*!c!jx4g#1@dxly)h0yw2=ul1-a!zng$d91$)"

# Fernet-nyckel för fältkryptering at rest (saldovibe/encryption.py). Sätt den
# uttryckligen i produktion: fallbacken härleds ur SECRET_KEY, så ett byte av
# DJANGO_SECRET_KEY utan satt nyckel gör krypterade fält oläsbara.
FIELD_ENCRYPTION_KEY = (
    os.getenv("SALDOVIBE_FIELD_ENCRYPTION_KEY")
    or base64.urlsafe_b64encode(hashlib.sha256(SECRET_KEY.encode()).digest()).decode()
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = _allowed_hosts()

CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins()

USE_X_FORWARDED_HOST = _env_flag("DJANGO_USE_X_FORWARDED_HOST", default=True)
if _env_flag("DJANGO_USE_SECURE_PROXY_SSL_HEADER", default=True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_COOKIE_SECURE = _env_flag("DJANGO_CSRF_COOKIE_SECURE", default=False)
SESSION_COOKIE_SECURE = _env_flag("DJANGO_SESSION_COOKIE_SECURE", default=False)
CSRF_FAILURE_VIEW = "saldovibe.csrf.csrf_failure"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "auditlog",
    "bookkeeping",
    "attachments",
    "supplier_invoices",
    "expenses",
    "banking",
    "invoicing",
    "payroll",
    "vat",
    "fixed_assets",
]

AUTH_USER_MODEL = "accounts.CustomUser"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "bookkeeping:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "saldovibe.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "bookkeeping.context_processors.active_company",
                "bookkeeping.context_processors.environment",
            ],
        },
    },
]

WSGI_APPLICATION = "saldovibe.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "django.db.backends.sqlite3")

if DATABASE_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": DATA_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": os.getenv("DATABASE_NAME", "saldovibe"),
            "USER": os.getenv("DATABASE_USER", "saldovibe"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", ""),
            "HOST": os.getenv("DATABASE_HOST", "localhost"),
            "PORT": os.getenv("DATABASE_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "sv-se"

# Svensk lokal tid: styr vilket datum formulär förifyller (verifikationsdatum,
# betalningsdatum) och hur tidsstämplar visas. Lagring sker fortfarande i UTC (USE_TZ).
TIME_ZONE = "Europe/Stockholm"

USE_I18N = True

# USE_THOUSAND_SEPARATOR applies locale grouping to *every* bare numeric template
# variable, not just money amounts — including primary keys used in <option value>,
# data-* attributes, and URL query params, corrupting them with a non-breaking space
# once the id reaches 4 digits. Money/amount displays instead force grouping
# explicitly via `|floatformat:'Ng'` (which groups regardless of this setting), so
# turning it off only removes accidental grouping of things that were never meant to
# be grouped.
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = " "
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.getenv("SALDOVIBE_STATIC_ROOT", str(DATA_DIR / "staticfiles")))
_VENDOR_STATICFILES_DIRS = [
    ("vendor/bootstrap", BASE_DIR / "node_modules" / "bootstrap" / "dist"),
    ("vendor/bootstrap-icons", BASE_DIR / "node_modules" / "bootstrap-icons" / "font"),
    ("vendor/chart.js", BASE_DIR / "node_modules" / "chart.js" / "dist"),
    ("vendor/jquery", BASE_DIR / "node_modules" / "jquery" / "dist"),
    ("vendor/select2", BASE_DIR / "node_modules" / "select2" / "dist"),
]

STATICFILES_DIRS = [BASE_DIR / "static"]

# node_modules is build-time only: the builder stage runs npm ci + collectstatic, and the
# runtime image copies the collected output but not node_modules itself. Listing the vendor
# dirs unconditionally therefore fires staticfiles.W004 five times on every management command
# in production, which is pure noise there -- the manifest is already built. Skip them when
# node_modules is absent as a whole (the runtime image), but keep an individually missing
# subdirectory in the list, so a real mismatch between package.json and these paths still warns
# during the build rather than silently writing a manifest with no vendor/ entries.
if (BASE_DIR / "node_modules").is_dir():
    STATICFILES_DIRS += _VENDOR_STATICFILES_DIRS

MEDIA_URL = "/media/"
MEDIA_ROOT = DATA_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

SERVE_STATIC = DEBUG
SERVE_MEDIA = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "attachments": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "attachments.email_import": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "bookkeeping": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Skatteverket API integration (set in environment for live lookups)
SKATTEVERKET_API_BASE_URL = os.getenv(
    "SKATTEVERKET_API_BASE_URL",
    "https://skatteverket.entryscape.net/rowstore/dataset/88320397-5c32-4c16-ae79-d36d95b17b95/html",
)
SKATTEVERKET_API_TAX_PATH = os.getenv("SKATTEVERKET_API_TAX_PATH", "")
SKATTEVERKET_API_KEY = os.getenv("SKATTEVERKET_API_KEY", "")
SKATTEVERKET_API_BEARER_TOKEN = os.getenv("SKATTEVERKET_API_BEARER_TOKEN", "")
SKATTEVERKET_API_TIMEOUT = int(os.getenv("SKATTEVERKET_API_TIMEOUT", "12"))
SKATTEVERKET_API_STRICT = os.getenv("SKATTEVERKET_API_STRICT", "0") in {"1", "true", "True"}


# Globalt systemkonto för utgående e-post (notisdigest, se bookkeeping/outgoing_mail.py).
# Kundriktad e-post (fakturor/påminnelser) skickas via företagets eget konto, inte detta.
# Tomt EMAIL_HOST = konsol-backend: dev och okonfigurerad prod skriver mail till loggen.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_flag("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "saldovibe@localhost")
if not EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ReInvGrabber: föreslår bokförings-/betalningsfält ur en uppladdad bilaga med
# lokal OCR, i samma process som SaldoVibe (se attachments/extraction_client.py
# och extraction/-paketet i requirements.txt). Av = ingen extraktion körs alls,
# bilageuppladdning fungerar precis som innan integrationen.
REINVGRABBER_ENABLED = os.getenv("REINVGRABBER_ENABLED", "1") in {"1", "true", "True"}
SKATTEVERKET_CA_BUNDLE = os.getenv("SKATTEVERKET_CA_BUNDLE", "")
SKATTEVERKET_USE_CERTIFI = os.getenv("SKATTEVERKET_USE_CERTIFI", "1") in {"1", "true", "True"}


# RFC 3161 timestamp authority used to externally anchor the audit hash chain
# (see auditlog/timestamping.py). Default is FreeTSA, a free public TSA - point
# this at a different/paid TSA in production if a stronger SLA is wanted. The
# CA cert is used to verify tokens offline via `openssl ts -verify`.
AUDIT_CHAIN_TSA_URL = os.getenv("AUDIT_CHAIN_TSA_URL", "https://freetsa.org/tsr")
AUDIT_CHAIN_TSA_CA_CERT = os.getenv(
    "AUDIT_CHAIN_TSA_CA_CERT",
    str(BASE_DIR / "auditlog" / "data" / "freetsa_cacert.pem"),
)
AUDIT_CHAIN_TSA_HASHNAME = os.getenv("AUDIT_CHAIN_TSA_HASHNAME", "sha256")
AUDIT_CHAIN_TSA_TIMEOUT = int(os.getenv("AUDIT_CHAIN_TSA_TIMEOUT", "15"))
