# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
        ('bookkeeping', '0002_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='Namn')),
                ('description', models.CharField(max_length=255, verbose_name='Beskrivning')),
                ('expense_date', models.DateField(verbose_name='Utläggsdatum')),
                ('amount_ex_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Belopp exkl. moms')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Moms')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Totalbelopp')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Bokförd')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Bokförd vid')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Utbetald')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Utbetalt belopp')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Utbetald vid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Utbetalningsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('attachments', models.ManyToManyField(blank=True, related_name='expense_claims', to='attachments.transactionattachment', verbose_name='Kvitton')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='bookkeeping.company', verbose_name='Företag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_claims', to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='payroll.employee', verbose_name='Anställd')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_costs', to='bookkeeping.account', verbose_name='Kostnadskonto')),
                ('liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_liabilities', to='bookkeeping.account', verbose_name='Skuldkonto')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_payments', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_payment_transactions', to='bookkeeping.transaction', verbose_name='Senaste betalningsverifikation')),
                ('registered_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='bookkeeping.transaction', verbose_name='Verifikation')),
                ('vat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_vat', to='bookkeeping.account', verbose_name='Momskonto')),
            ],
            options={
                'verbose_name': 'Utlägg',
                'verbose_name_plural': 'Utlägg',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Avskrivet belopp')),
                ('payment_date', models.DateField(verbose_name='Betalningsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ångrad vid')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenseclaim', verbose_name='Utlägg')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_payment_rows', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('reversal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.transaction', verbose_name='Korrigeringsverifikation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_payment_rows', to='bookkeeping.transaction', verbose_name='Verifikation')),
            ],
            options={
                'verbose_name': 'Utläggsbetalning',
                'verbose_name_plural': 'Utläggsbetalningar',
                'ordering': ['payment_date', 'id'],
                'abstract': False,
            },
        ),
    ]
