# Generated by Django 5.2.17 on 2026-09-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('payroll', '0003_vacation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='salary_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='payroll.salaryrecord', verbose_name='Betalas ut via lönepost'),
        ),
    ]
