# Generated by Django 5.2.17 on 2026-10-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_company_email_fetch_imap'),
        ('expenses', '0002_expenseclaim_salary_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namn')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='bookkeeping.account', verbose_name='Konto')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Utläggskategori',
                'verbose_name_plural': 'Utläggskategorier',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='expenses.expensecategory', verbose_name='Kategori'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_expense_category_name'),
        ),
    ]
