# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchored_entry_hash', models.CharField(help_text='entry_hash-värdet vid tidpunkten för förankringen, bevarat även om posten senare ändras.', max_length=64, verbose_name='Förankrad hash')),
                ('tsa_url', models.CharField(max_length=255, verbose_name='TSA-URL')),
                ('timestamp_token', models.BinaryField(verbose_name='Tidsstämpeltoken (RFC 3161)')),
                ('tsa_asserted_time', models.DateTimeField(verbose_name='TSA:s tidsstämpel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
            ],
            options={
                'verbose_name': 'Auditkedje-förankring',
                'verbose_name_plural': 'Auditkedje-förankringar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditChainTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_key', models.CharField(max_length=32, unique=True, verbose_name='Kedjenyckel')),
            ],
            options={
                'verbose_name': 'Auditkedje-spets',
                'verbose_name_plural': 'Auditkedje-spetsar',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Tidpunkt')),
                ('action', models.CharField(choices=[('create', 'Skapad'), ('update', 'Uppdaterad'), ('delete', 'Raderad')], max_length=12, verbose_name='Händelse')),
                ('actor_display', models.CharField(blank=True, max_length=255, verbose_name='Användare')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Företagsnamn')),
                ('chain_key', models.CharField(blank=True, default='', max_length=32, verbose_name='Kedjenyckel')),
                ('model_label', models.CharField(max_length=120, verbose_name='Modell')),
                ('model_name', models.CharField(max_length=120, verbose_name='Objekttyp')),
                ('object_pk', models.CharField(max_length=64, verbose_name='Objekt-ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Objekt')),
                ('summary', models.CharField(max_length=255, verbose_name='Sammanfattning')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Ändringar')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('hash_version', models.PositiveSmallIntegerField(default=1, verbose_name='Hashversion')),
                ('prev_hash', models.CharField(blank=True, max_length=64, verbose_name='Föregående hash')),
                ('entry_hash', models.CharField(blank=True, max_length=64, verbose_name='Entry hash')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
            options={
                'verbose_name': 'Logghändelse',
                'verbose_name_plural': 'Logghändelser',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
