# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0001_initial'),
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='auditchainanchor',
            name='anchored_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_anchors', to='auditlog.auditlogentry', verbose_name='Förankrad logghändelse'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['company', 'occurred_at'], name='auditlog_au_company_d9f29d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['chain_key', 'id'], name='auditlog_au_chain_k_0a6f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['model_label', 'occurred_at'], name='auditlog_au_model_l_f63233_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', 'occurred_at'], name='auditlog_au_action_872668_idx'),
        ),
    ]
