from django.urls import path

from . import views

app_name = "bookkeeping"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("topbar/status/", views.topbar_alert_status, name="topbar_alert_status"),
    path("sok/", views.search, name="search"),
    path(
        "likviditetsprognos/konton/",
        views.liquidity_forecast_accounts,
        name="liquidity_forecast_accounts",
    ),
    path("compliance/", views.compliance_dashboard, name="compliance_dashboard"),
    path("compliance/systemdokumentation/", views.system_documentation, name="system_documentation"),
    path("compliance/systemdokumentation/pdf/", views.system_documentation_pdf, name="system_documentation_pdf"),
    path("hjalp/", views.help_index, name="help_index"),
    path("hjalp/<slug:slug>/", views.help_chapter, name="help_chapter"),
    path("foretag/", views.company_list, name="company_list"),
    path("foretag/ny/", views.company_create, name="company_create"),
    path("foretag/ingen-atkomst/", views.no_company_access, name="no_company_access"),
    path("foretag/valj/", views.select_company, name="select_company"),
    path("foretag/<int:pk>/uppdatera/", views.company_update, name="company_update"),
    path("foretag/<int:pk>/ta-bort/", views.company_delete, name="company_delete"),
    path("foretag/<int:pk>/anvandare/", views.company_members, name="company_members"),
    path(
        "foretag/<int:pk>/anvandare/<int:user_id>/ta-bort/",
        views.company_member_remove,
        name="company_member_remove",
    ),
    path("foretag/byt/", views.switch_company, name="switch_company"),
    path("rakenskapsar/", views.accounting_year_list, name="accounting_year_list"),
    path("rakenskapsar/ny/", views.accounting_year_create, name="accounting_year_create"),
    path("rakenskapsar/<int:pk>/redigera/", views.accounting_year_update, name="accounting_year_update"),
    path("rakenskapsar/<int:pk>/ta-bort/", views.accounting_year_delete, name="accounting_year_delete"),
    path("rakenskapsar/<int:pk>/las-hela-aret/", views.period_lock_lock_year, name="period_lock_lock_year"),
    path("rakenskapsar/<int:pk>/bokslut/", views.year_end_close, name="year_end_close"),
    path("periodlasning/", views.period_lock_list, name="period_lock_list"),
    path("periodlasning/ny/", views.period_lock_create, name="period_lock_create"),
    path("periodlasning/<int:pk>/las-upp/", views.period_lock_reopen, name="period_lock_reopen"),
    path("periodlasning/<int:pk>/las-om/", views.period_lock_relock, name="period_lock_relock"),
    path("transaktioner/", views.transaction_list, name="transaction_list"),
    path("transaktioner/ny/", views.transaction_add, name="transaction_add"),
    path("transaktioner/periodisering/", views.periodization_create, name="periodization_create"),
    path("transaktioner/mallar/", views.verification_template_list, name="verification_template_list"),
    path("transaktioner/mallar/ny/", views.verification_template_create, name="verification_template_create"),
    path(
        "transaktioner/mallar/bibliotek/",
        views.verification_template_library,
        name="verification_template_library",
    ),
    path(
        "transaktioner/mallar/<int:pk>/redigera/",
        views.verification_template_update,
        name="verification_template_update",
    ),
    path(
        "transaktioner/mallar/<int:pk>/ta-bort/",
        views.verification_template_delete,
        name="verification_template_delete",
    ),
    path("verifikationsserier/", views.voucher_series_settings, name="voucher_series_settings"),
    path("transaktioner/import/sie/", views.sie_import, name="sie_import"),
    path(
        "transaktioner/import/sie/diagnostik/",
        views.sie_import_diagnostics_download,
        name="sie_import_diagnostics_download",
    ),
    path("transaktioner/import/si/", views.si_import, name="si_import"),
    path(
        "transaktioner/import/si/diagnostik/",
        views.si_import_diagnostics_download,
        name="si_import_diagnostics_download",
    ),
    path("transaktioner/export/sie4/", views.sie_export, name="sie_export"),
    path("transaktioner/<int:pk>/korrigera/", views.transaction_reverse, name="transaction_reverse"),
    path(
        "transaktioner/<int:pk>/bilagor/lagg-till/",
        views.transaction_attachment_add,
        name="transaction_attachment_add",
    ),
    path(
        "transaktioner/<int:pk>/bilagor/ta-bort/",
        views.transaction_attachment_remove,
        name="transaction_attachment_remove",
    ),
    path("transaktioner/<int:pk>/", views.transaction_detail, name="transaction_detail"),
    path("balansrakning/", views.balance_sheet, name="balance_sheet"),
    path("balansrakning/pdf/", views.balance_sheet_pdf, name="balance_sheet_pdf"),
    path("resultatrakning/", views.income_statement, name="income_statement"),
    path("resultatrakning/pdf/", views.income_statement_pdf, name="income_statement_pdf"),
    path("huvudbok/", views.general_ledger, name="general_ledger"),
    path("huvudbok/pdf/", views.general_ledger_pdf, name="general_ledger_pdf"),
    path("reskontra/", views.reskontra, name="reskontra"),
    path("reskontra/pdf/", views.reskontra_pdf, name="reskontra_pdf"),
    path("resultatrakning/budget/<int:pk>/", views.budget_edit, name="budget_edit"),
    path("konton/", views.account_list, name="account_list"),
    path("konton/ny/", views.account_create, name="account_create"),
    path("konton/forslag/", views.account_suggest_codes, name="account_suggest_codes"),
    path("konton/saldon/", views.account_balances_lookup, name="account_balances_lookup"),
    path("konton/<int:pk>/redigera/", views.account_update, name="account_update"),
    path("sru/", views.sru_report, name="sru_report"),
    path("sru/ladda-ner/", views.sru_download, name="sru_download"),
    path("sru/validering/rapport/", views.sru_preflight_report_download, name="sru_preflight_report_download"),
    path("export/", views.export_bundle_form, name="export_bundle"),
    path("export/starta/", views.export_bundle_start, name="export_bundle_start"),
    path("export/<int:job_id>/ladda-ner/", views.export_bundle_download, name="export_bundle_download"),
    path("export/<int:job_id>/ta-bort/", views.export_bundle_delete, name="export_bundle_delete"),
]
