# Generated by Django 5.2.17 on 2026-10-05 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Enhet')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Tokenhash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Senast använd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appinloggning',
                'verbose_name_plural': 'Appinloggningar',
                'ordering': ['-created_at'],
            },
        ),
    ]
