# Generated by Django 5.2.17 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Namn')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='Kontonummer')),
                ('account_type', models.CharField(choices=[('bank', 'Bankkonto'), ('tax', 'Skattekonto'), ('savings', 'Sparkonto'), ('credit_card', 'Kreditkort')], max_length=20, verbose_name='Typ')),
                ('default_bank_profile', models.CharField(choices=[('auto', 'Auto (försök känna igen format)'), ('generic', 'Generisk CSV'), ('skatteverket', 'Skatteverket (skattekonto CSV)'), ('swedbank', 'Swedbank / Sparbankerna (otestad)'), ('nordea', 'Nordea (otestad)'), ('seb', 'SEB (otestad)'), ('handelsbanken', 'Handelsbanken'), ('danske_bank', 'Danske Bank (otestad)'), ('lansforsakringar', 'Länsförsäkringar Bank (otestad)'), ('skandiabanken', 'Skandia / Skandiabanken (otestad)'), ('ica_banken', 'ICA Banken (otestad)'), ('avanza', 'Avanza Bank (otestad)'), ('nordnet', 'Nordnet Bank (otestad)'), ('svea', 'Svea Bank (otestad)'), ('resurs', 'Resurs Bank (otestad)'), ('marginalen', 'Marginalen Bank'), ('collector', 'Collector Bank (otestad)')], default='auto', max_length=30, verbose_name='Standardformat CSV')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bankkälla',
                'verbose_name_plural': 'Bankkällor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='CSV', max_length=100, verbose_name='Källa')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importerad')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Importer',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('description', models.CharField(max_length=500, verbose_name='Text')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo')),
                ('external_id', models.CharField(max_length=120, verbose_name='Externt ID')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Bokförd')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bokförd vid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banktransaktion',
                'verbose_name_plural': 'Banktransaktioner',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
