# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bookkeeping_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_connections', to='bookkeeping.account', verbose_name='Bokföringskonto'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='banking.bankaccount', verbose_name='Bankkälla'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_imports', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importerad av'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount', verbose_name='Bankkälla'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='booked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction_sources', to='bookkeeping.transaction', verbose_name='Verifikation'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='bookkeeping.company', verbose_name='Företag'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.bankimport', verbose_name='Import'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_bank_account_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'tax')), fields=('company',), name='uniq_tax_bank_account_per_company'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('company', 'bank_account', 'external_id'), name='uniq_bank_tx_external_id_per_company_account'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('booked_transaction__isnull', False)), fields=('bank_account', 'booked_transaction'), name='uniq_bank_tx_per_account_per_verification'),
        ),
    ]
