# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=50, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Artikel')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('unit', models.CharField(default='st', max_length=20, verbose_name='Enhet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Á-pris')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='Moms %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bookkeeping.company', verbose_name='Företag')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_articles', to='bookkeeping.account', verbose_name='Intäktskonto')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artiklar',
                'ordering': ['article_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kundnamn')),
                ('org_number', models.CharField(blank=True, max_length=50, verbose_name='Organisationsnummer')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='Momsregistreringsnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adress')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postnummer')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('country_code', models.CharField(blank=True, default='SE', max_length=2, verbose_name='Landskod (ISO 3166-1 alpha-2)')),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Standard betalningsvillkor (dagar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Kund',
                'verbose_name_plural': 'Kunder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, verbose_name='Fakturanummer')),
                ('ocr_code', models.CharField(blank=True, max_length=50, verbose_name='OCR')),
                ('invoice_date', models.DateField(verbose_name='Fakturadatum')),
                ('due_date', models.DateField(verbose_name='Förfallodatum')),
                ('delivery_date', models.DateField(blank=True, help_text='Ange endast om leveransdatumet skiljer sig från fakturadatumet (krav enligt 11 kap. mervärdesskattelagen).', null=True, verbose_name='Leverans-/tillhandahållandedatum')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Betalningsvillkor (dagar)')),
                ('currency', models.CharField(default='SEK', max_length=3, verbose_name='Valuta')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Er referens')),
                ('reverse_charge', models.BooleanField(default=False, help_text='Köparen är skattskyldig för momsen. Fakturan får då inte innehålla något momsbelopp.', verbose_name='Omvänd betalningsskyldighet')),
                ('notes', models.TextField(blank=True, verbose_name='Notering')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Bokförd')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bokförd vid')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Betald')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Betalt belopp')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Betald vid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Betalningsdatum')),
                ('recurring_period_label', models.CharField(blank=True, max_length=100, verbose_name='Period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_invoices', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('attachments', models.ManyToManyField(blank=True, related_name='sales_invoices', to='attachments.transactionattachment', verbose_name='Bilagor')),
                ('booked_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_invoice', to='bookkeeping.transaction', verbose_name='Verifikation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_invoices', to='bookkeeping.company', verbose_name='Företag')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.customer', verbose_name='Kund')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_payments', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_invoice_payments', to='bookkeeping.transaction', verbose_name='Senaste betalningsverifikation')),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_receivable_invoices', to='bookkeeping.account', verbose_name='Kundfordringskonto')),
            ],
            options={
                'verbose_name': 'Kundfaktura',
                'verbose_name_plural': 'Kundfakturor',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beskrivning')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Antal')),
                ('unit', models.CharField(default='st', max_length=20, verbose_name='Enhet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Á-pris')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='Moms %')),
                ('line_type', models.CharField(choices=[('item', 'Artikelrad'), ('text', 'Textrad')], default='item', max_length=10, verbose_name='Radtyp')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='invoicing.article', verbose_name='Artikel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Faktura')),
            ],
            options={
                'verbose_name': 'Fakturarad',
                'verbose_name_plural': 'Fakturarader',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_number_sequences', to='bookkeeping.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Avskrivet belopp')),
                ('payment_date', models.DateField(verbose_name='Betalningsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ångrad vid')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice', verbose_name='Faktura')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_payment_rows', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('reversal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.transaction', verbose_name='Korrigeringsverifikation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoice_payment_rows', to='bookkeeping.transaction', verbose_name='Verifikation')),
            ],
            options={
                'verbose_name': 'Fakturabetalning',
                'verbose_name_plural': 'Fakturabetalningar',
                'ordering': ['payment_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Påminnelseavgift')),
                ('pay_by_date', models.DateField(verbose_name='Betala senast')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoicing.invoice', verbose_name='Faktura')),
            ],
            options={
                'verbose_name': 'Betalningspåminnelse',
                'verbose_name_plural': 'Betalningspåminnelser',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mallnamn')),
                ('interval', models.CharField(choices=[('monthly', 'Månadsvis'), ('quarterly', 'Kvartalsvis'), ('semiannual', 'Halvårsvis'), ('annual', 'Årsvis'), ('custom_months', 'Eget antal månader')], default='monthly', max_length=20, verbose_name='Intervall')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Eget antal månader')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('anchor_to_month_end', models.BooleanField(default=False, verbose_name='Alltid sista dagen i månaden')),
                ('next_run_date', models.DateField(verbose_name='Nästa fakturadatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Slutdatum')),
                ('due_date_mode', models.CharField(choices=[('days_after', 'Antal dagar efter fakturadatum'), ('day_of_month', 'Fast dag i månaden')], default='days_after', max_length=20, verbose_name='Förfallodatum')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Betalningsvillkor (dagar)')),
                ('due_date_day_of_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dag i månaden')),
                ('due_date_last_day_of_month', models.BooleanField(default=False, verbose_name='Sista dagen i månaden')),
                ('period_reference', models.CharField(choices=[('previous', 'Föregående period'), ('current', 'Aktuell period'), ('next', 'Kommande period')], default='current', max_length=10, verbose_name='Period')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Er referens')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('occurrences_generated', models.PositiveIntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Senast genererad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='bookkeeping.company', verbose_name='Företag')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='invoicing.customer', verbose_name='Kund')),
            ],
            options={
                'verbose_name': 'Återkommande faktura',
                'verbose_name_plural': 'Återkommande fakturor',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='invoicing.recurringinvoice', verbose_name='Återkommande mall'),
        ),
        migrations.CreateModel(
            name='RecurringInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beskrivning')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Antal')),
                ('unit', models.CharField(default='st', max_length=20, verbose_name='Enhet')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Á-pris')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='Moms %')),
                ('line_type', models.CharField(choices=[('item', 'Artikelrad'), ('text', 'Textrad')], default='item', max_length=10, verbose_name='Radtyp')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoice_lines', to='invoicing.article', verbose_name='Artikel')),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.recurringinvoice', verbose_name='Mall')),
            ],
            options={
                'verbose_name': 'Mallrad',
                'verbose_name_plural': 'Mallrader',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('article_number', ''), _negated=True), fields=('company', 'article_number'), name='uniq_article_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_customer_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('company', 'year'), name='uniq_invoice_number_sequence_per_company_year'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_recurring_invoice_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_invoice_number_per_company'),
        ),
    ]
