# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('asset_type', models.CharField(max_length=40, verbose_name='Typ')),
                ('acquisition_date', models.DateField(verbose_name='Inköpsdatum')),
                ('depreciation_start_date', models.DateField(verbose_name='Start avskrivning')),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Anskaffningsvärde')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Restvärde')),
                ('useful_life_months', models.PositiveIntegerField(verbose_name='Nyttjandeperiod (månader)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Anteckningar')),
                ('disposed_at', models.DateField(blank=True, null=True, verbose_name='Utrangerings-/avyttringsdatum')),
                ('disposal_type', models.CharField(blank=True, choices=[('scrapped', 'Utrangerad (skrotad)'), ('sold', 'Såld/avyttrad'), ('other', 'Övrigt')], max_length=20, verbose_name='Typ av avgång')),
                ('disposal_reason', models.TextField(blank=True, verbose_name='Anledning till avgång')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='bookkeeping.company', verbose_name='Företag')),
                ('disposal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_disposals', to='bookkeeping.transaction', verbose_name='Avgångsverifikation')),
            ],
            options={
                'verbose_name': 'Anläggningstillgång',
                'verbose_name_plural': 'Anläggningstillgångar',
                'ordering': ['-depreciation_start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetReclassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ändrad')),
                ('from_asset_type', models.CharField(max_length=40, verbose_name='Från typ')),
                ('to_asset_type', models.CharField(max_length=40, verbose_name='Till typ')),
                ('reason', models.TextField(blank=True, verbose_name='Anledning')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_reclassifications', to=settings.AUTH_USER_MODEL, verbose_name='Ändrad av')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclassification_entries', to='fixed_assets.fixedasset', verbose_name='Anläggningstillgång')),
            ],
            options={
                'verbose_name': 'Omklassificering',
                'verbose_name_plural': 'Omklassificeringar',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('is_correction', models.BooleanField(default=False, verbose_name='Är korrigering')),
                ('reason', models.TextField(blank=True, verbose_name='Anledning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='fixed_assets.fixedassetdepreciation', verbose_name='Korrigering av')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='fixed_assets.fixedasset', verbose_name='Anläggningstillgång')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_depreciation', to='bookkeeping.transaction', verbose_name='Verifikation')),
            ],
            options={
                'verbose_name': 'Avskrivning',
                'verbose_name_plural': 'Avskrivningar',
                'ordering': ['-period', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_correction', False)), fields=('fixed_asset', 'period'), name='uniq_fixed_asset_depreciation_period')],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetImpairment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('is_correction', models.BooleanField(default=False, verbose_name='Är korrigering')),
                ('reason', models.TextField(verbose_name='Anledning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='fixed_assets.fixedassetimpairment', verbose_name='Korrigering av')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impairment_entries', to='fixed_assets.fixedasset', verbose_name='Anläggningstillgång')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_impairment', to='bookkeeping.transaction', verbose_name='Verifikation')),
            ],
            options={
                'verbose_name': 'Nedskrivning',
                'verbose_name_plural': 'Nedskrivningar',
                'ordering': ['-period', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_correction', False)), fields=('fixed_asset', 'period'), name='uniq_fixed_asset_impairment_period')],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='Nyckel')),
                ('name', models.CharField(max_length=120, verbose_name='Namn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sorteringsordning')),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_accumulated', to='bookkeeping.account', verbose_name='Ackumulerad avskrivning (kredit)')),
                ('accumulated_impairment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_accumulated_impairment', to='bookkeeping.account', verbose_name='Ackumulerad nedskrivning (kredit)')),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_asset', to='bookkeeping.account', verbose_name='Tillgångskonto')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_asset_types', to='bookkeeping.company', verbose_name='Företag')),
                ('depreciation_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_expense', to='bookkeeping.account', verbose_name='Avskrivningskonto (debet)')),
                ('disposal_gain_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_disposal_gain', to='bookkeeping.account', verbose_name='Vinst vid avyttring (kredit)')),
                ('disposal_loss_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_disposal_loss', to='bookkeeping.account', verbose_name='Förlust vid avyttring (debet)')),
                ('impairment_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_type_impairment_expense', to='bookkeeping.account', verbose_name='Nedskrivningskostnad (debet)')),
            ],
            options={
                'verbose_name': 'Anläggningstillgångstyp',
                'verbose_name_plural': 'Anläggningstillgångstyper',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='uniq_fixed_asset_type_key_per_company')],
            },
        ),
    ]
