# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.core.validators
import django.db.models.deletion
import saldovibe.encryption
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Förnamn')),
                ('last_name', models.CharField(max_length=120, verbose_name='Efternamn')),
                ('personal_identity_number', saldovibe.encryption.EncryptedTextField(validators=[django.core.validators.MaxLengthValidator(12)], verbose_name='Personnummer')),
                ('personal_identity_number_hash', models.CharField(default='', editable=False, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adress')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postnummer')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Månadslön')),
                ('employment_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Sysselsättningsgrad (%)')),
                ('tax_table_number', models.PositiveSmallIntegerField(default=32, verbose_name='Skattetabell')),
                ('tax_table_column', models.PositiveSmallIntegerField(choices=[(1, 'Kolumn 1 - Lön, arvode och liknande ersättning (huvudinkomst)'), (2, 'Kolumn 2 - Pension och andra pensionsgrundande ersättningar'), (3, 'Kolumn 3 - Lön till personer som fyllt 66 år vid årets ingång'), (4, 'Kolumn 4 - Pension till personer som fyllt 66 år vid årets ingång'), (5, 'Kolumn 5 - Andra skattepliktiga ersättningar'), (6, 'Kolumn 6 - Särskilda fall enligt Skatteverkets tabell')], default=1, verbose_name='Kolumn')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Anställningsdatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Anställd',
                'verbose_name_plural': 'Anställda',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDefaultAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre_tax', 'Före skatt'), ('post_tax', 'Efter skatt')], default='pre_tax', max_length=20, verbose_name='Tidpunkt')),
                ('direction', models.CharField(choices=[('addition', 'Tillägg'), ('deduction', 'Avdrag')], default='addition', max_length=20, verbose_name='Typ')),
                ('category', models.CharField(blank=True, choices=[('', 'Övrigt'), ('taxable_benefit', 'Skattepliktig förmån'), ('ob_supplement', 'OB-tillägg'), ('overtime', 'Övertidsersättning'), ('bonus', 'Bonus'), ('gross_salary_deduction', 'Bruttolöneavdrag'), ('tax_free_mileage', 'Skattefri milersättning'), ('net_salary_deduction', 'Nettolöneavdrag')], default='', max_length=30, verbose_name='Kategori')),
                ('description', models.CharField(max_length=200, verbose_name='Beskrivning')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Belopp')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Skattepliktig')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_adjustments', to='payroll.employee', verbose_name='Anställd')),
            ],
            options={
                'verbose_name': 'Standardjustering för anställd',
                'verbose_name_plural': 'Standardjusteringar för anställd',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField(verbose_name='År')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Månad')),
                ('payment_date', models.DateField(verbose_name='Utbetalningsdatum')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Avslutad')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Avslutad tidpunkt')),
                ('is_reported_to_skatteverket', models.BooleanField(default=False, verbose_name='Rapporterad till Skatteverket')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Rapporterad tidpunkt')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Utbetalt nettobelopp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run_booking', to='bookkeeping.transaction', verbose_name='Bokföringsverifikation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='bookkeeping.company', verbose_name='Företag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Avslutad av')),
            ],
            options={
                'verbose_name': 'Lönekörning',
                'verbose_name_plural': 'Lönekörningar',
                'ordering': ['-period_year', '-period_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_json', models.TextField(verbose_name='AGI-underlag (JSON)')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='SHA256')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Genererad')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_report_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Genererad av')),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report_evidence', to='payroll.payrollrun', verbose_name='Lönekörning')),
            ],
            options={
                'verbose_name': 'AGI-bevispaket',
                'verbose_name_plural': 'AGI-bevispaket',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Förfallodatum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Belopp')),
                ('description', models.CharField(max_length=300, verbose_name='Beskrivning')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Utförd')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Utförd tidpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payment_reminders', to='bookkeeping.company', verbose_name='Företag')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payment_reminders', to='payroll.employee', verbose_name='Anställd')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='payroll.payrollrun', verbose_name='Lönekörning')),
            ],
            options={
                'verbose_name': 'Lönepåminnelse',
                'verbose_name_plural': 'Lönepåminnelser',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bruttolön')),
                ('taxable_additions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Skattepliktiga tillägg')),
                ('non_taxable_additions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Skattefria tillägg')),
                ('pre_tax_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Avdrag före skatt')),
                ('post_tax_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Avdrag efter skatt')),
                ('tax_table_number', models.PositiveSmallIntegerField(default=32, verbose_name='Skattetabell')),
                ('tax_table_column', models.PositiveSmallIntegerField(choices=[(1, 'Kolumn 1 - Lön, arvode och liknande ersättning (huvudinkomst)'), (2, 'Kolumn 2 - Pension och andra pensionsgrundande ersättningar'), (3, 'Kolumn 3 - Lön till personer som fyllt 66 år vid årets ingång'), (4, 'Kolumn 4 - Pension till personer som fyllt 66 år vid årets ingång'), (5, 'Kolumn 5 - Andra skattepliktiga ersättningar'), (6, 'Kolumn 6 - Särskilda fall enligt Skatteverkets tabell')], default=1, verbose_name='Kolumn')),
                ('preliminary_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Preliminärskatt (%)')),
                ('preliminary_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Skatteavdrag')),
                ('tax_calculation_source', models.CharField(choices=[('api', 'Skatteverket API'), ('table_fallback', 'Intern tabellberäkning (utfasad)')], default='api', max_length=20, verbose_name='Skattekälla')),
                ('tax_calculation_reference', models.CharField(blank=True, max_length=120, verbose_name='Skattereferens')),
                ('employer_contribution_rate', models.DecimalField(decimal_places=2, default=Decimal('31.42'), max_digits=5, verbose_name='Arbetsgivaravgift (%)')),
                ('employer_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Arbetsgivaravgift')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Nettolön')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='payroll.employee', verbose_name='Anställd')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='payroll.payrollrun', verbose_name='Lönekörning')),
            ],
            options={
                'verbose_name': 'Lönepost',
                'verbose_name_plural': 'Löneposter',
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre_tax', 'Före skatt'), ('post_tax', 'Efter skatt')], default='pre_tax', max_length=20, verbose_name='Tidpunkt')),
                ('direction', models.CharField(choices=[('addition', 'Tillägg'), ('deduction', 'Avdrag')], default='addition', max_length=20, verbose_name='Typ')),
                ('category', models.CharField(blank=True, choices=[('', 'Övrigt'), ('taxable_benefit', 'Skattepliktig förmån'), ('ob_supplement', 'OB-tillägg'), ('overtime', 'Övertidsersättning'), ('bonus', 'Bonus'), ('gross_salary_deduction', 'Bruttolöneavdrag'), ('tax_free_mileage', 'Skattefri milersättning'), ('net_salary_deduction', 'Nettolöneavdrag')], default='', max_length=30, verbose_name='Kategori')),
                ('description', models.CharField(max_length=200, verbose_name='Beskrivning')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Belopp')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Skattepliktig')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.salaryrecord', verbose_name='Lönepost')),
            ],
            options={
                'verbose_name': 'Lönejustering',
                'verbose_name_plural': 'Lönejusteringar',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'personal_identity_number_hash'), name='uniq_employee_pnr_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'period_year', 'period_month'), name='uniq_payroll_run_per_month'),
        ),
        migrations.AddConstraint(
            model_name='salarypaymentreminder',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='uniq_salary_payment_reminder_per_employee_and_run'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='uniq_salary_record_per_employee_and_run'),
        ),
    ]
