# Generated by Django 5.2.17 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Lönespecifikationen kan skickas hit.', max_length=254, verbose_name='E-post'),
        ),
    ]
