# Generated by Django 5.2.17 on 2026-09-07 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacation_days_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minskas automatiskt när en lönekörning med uttagna semesterdagar avslutas. Fyll på manuellt vid nytt semesterår.', max_digits=5, verbose_name='Kvarvarande semesterdagar'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='vacation_days_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Uttagna semesterdagar'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='vacation_supplement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Semestertillägg'),
        ),
    ]
