# Generated by Django 5.2.17 on 2026-09-30 22:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_company_email_fetch_imap'),
        ('expenses', '0002_expenseclaim_salary_record'),
        ('payroll', '0003_vacation_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(verbose_name='Datum')),
                ('route', models.CharField(help_text='T.ex. Stockholm–Uppsala t/r', max_length=200, verbose_name='Resväg')),
                ('purpose', models.CharField(max_length=200, verbose_name='Syfte')),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Sträcka (km)')),
                ('rate_per_mil', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6, verbose_name='Ersättning (kr/mil)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_reports', to='bookkeeping.company', verbose_name='Företag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mileage_reports', to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mileage_reports', to='payroll.employee', verbose_name='Anställd')),
                ('expense_claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_report', to='expenses.expenseclaim', verbose_name='Utlägg')),
            ],
            options={
                'verbose_name': 'Körrapport',
                'verbose_name_plural': 'Körrapporter',
                'ordering': ['-trip_date', '-id'],
            },
        ),
    ]
