# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('bookkeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('org_number', models.CharField(blank=True, max_length=50, verbose_name='Organisationsnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('bankgiro', models.CharField(blank=True, max_length=50, verbose_name='Bankgiro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='bookkeeping.company', verbose_name='Företag')),
            ],
            options={
                'verbose_name': 'Leverantör',
                'verbose_name_plural': 'Leverantörer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Leverantör')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Fakturanummer')),
                ('ocr_code', models.CharField(blank=True, max_length=50, verbose_name='OCR')),
                ('invoice_date', models.DateField(verbose_name='Fakturadatum')),
                ('due_date', models.DateField(verbose_name='Förfallodatum')),
                ('amount_ex_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Belopp exkl. moms')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Totalbelopp')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Moms')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Bokförd')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Bokförd vid')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Betald')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Betalt belopp')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Betald vid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Betalningsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='bookkeeping.accountingyear', verbose_name='Räkenskapsår')),
                ('attachments', models.ManyToManyField(blank=True, related_name='supplier_invoices', to='attachments.transactionattachment', verbose_name='Bilagor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='bookkeeping.company', verbose_name='Företag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_expense_invoices', to='bookkeeping.account', verbose_name='Kostnadskonto')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payable_invoices', to='bookkeeping.account', verbose_name='Skuldkonto')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payments', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_payment_transactions', to='bookkeeping.transaction', verbose_name='Senaste betalningsverifikation')),
                ('registered_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice', to='bookkeeping.transaction', verbose_name='Verifikation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='supplier_invoices.supplier', verbose_name='Leverantör')),
                ('vat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_vat_invoices', to='bookkeeping.account', verbose_name='Momskonto')),
            ],
            options={
                'verbose_name': 'Leverantörsfaktura',
                'verbose_name_plural': 'Leverantörsfakturor',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Debet')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Kredit')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_cost_lines', to='bookkeeping.account', verbose_name='Kostnadskonto')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='supplier_invoices.supplierinvoice', verbose_name='Leverantörsfaktura')),
            ],
            options={
                'verbose_name': 'Fakturarad',
                'verbose_name_plural': 'Fakturarader',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Belopp')),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Avskrivet belopp')),
                ('payment_date', models.DateField(verbose_name='Betalningsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ångrad vid')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supplier_invoices.supplierinvoice', verbose_name='Leverantörsfaktura')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payment_rows', to='bookkeeping.account', verbose_name='Betalkonto')),
                ('reversal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookkeeping.transaction', verbose_name='Korrigeringsverifikation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_payment_rows', to='bookkeeping.transaction', verbose_name='Verifikation')),
            ],
            options={
                'verbose_name': 'Leverantörsfakturabetalning',
                'verbose_name_plural': 'Leverantörsfakturabetalningar',
                'ordering': ['payment_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_supplier_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('company', 'invoice_number'), name='uniq_supplier_invoice_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicecostline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='supplier_invoice_cost_line_not_both_debit_and_credit'),
        ),
    ]
