# Generated by Django 5.2.17 on 2026-10-06 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_attachmentuploadtoken'),
        ('bookkeeping', '0006_company_email_fetch_imap'),
        ('supplier_invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierinvoice',
            name='uniq_supplier_invoice_number_per_company',
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('company', 'supplier', 'invoice_number'), name='uniq_supplier_invoice_number_per_supplier'),
        ),
    ]
