# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transaction_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Fil')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='transaction_attachment_thumbs/%Y/%m/', verbose_name='Miniatyr')),
                ('thumbnail_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Miniatyr skapad')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uppladdad')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Borttagen vid')),
                ('delete_reason', models.CharField(blank=True, max_length=255, verbose_name='Orsak borttagning')),
                ('source', models.CharField(choices=[('manual', 'Manuell'), ('email', 'E-post')], default='manual', max_length=20, verbose_name='Källa')),
                ('source_provider', models.CharField(blank=True, max_length=20)),
                ('source_message_id', models.CharField(blank=True, max_length=255)),
                ('source_attachment_id', models.CharField(blank=True, max_length=255)),
                ('source_email_subject', models.CharField(blank=True, max_length=255)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Innehållshash')),
                ('extracted_data', models.JSONField(blank=True, help_text='Belopp/moms/leverantör m.m. föreslagna av ReInvGrabber - bara ett förslag, aldrig bokförd data i sig. Null om integrationen är avstängd eller anropet misslyckades.', null=True, verbose_name='Föreslagna fält (ReInvGrabber)')),
            ],
            options={
                'verbose_name': 'Bilaga',
                'verbose_name_plural': 'Bilagor',
                'db_table': 'bookkeeping_transactionattachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
