# Generated by Django 5.2.17 on 2026-10-01 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
        ('bookkeeping', '0006_company_email_fetch_imap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentUploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Tokenhash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_tokens', to='bookkeeping.company', verbose_name='Företag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
            options={
                'verbose_name': 'Uppladdningstoken',
                'verbose_name_plural': 'Uppladdningstoken',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_upload_token_per_company_user')],
            },
        ),
    ]
